// <auto-generated />
using AutoServis.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AutoServis.Migrations
{
    [DbContext(typeof(MojContext))]
    [Migration("20180522134501_inicijalno")]
    partial class inicijalno
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoServis.Models.Dio", b =>
                {
                    b.Property<int>("DioId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Cijena");

                    b.Property<int>("ModelID");

                    b.Property<string>("Naziv");

                    b.Property<string>("Sifra");

                    b.HasKey("DioId");

                    b.HasIndex("ModelID");

                    b.ToTable("dio");
                });

            modelBuilder.Entity("AutoServis.Models.Marka", b =>
                {
                    b.Property<int>("MarkaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nazvi");

                    b.HasKey("MarkaId");

                    b.ToTable("marka");
                });

            modelBuilder.Entity("AutoServis.Models.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MarkaID");

                    b.Property<string>("Naziv");

                    b.HasKey("ModelId");

                    b.HasIndex("MarkaID");

                    b.ToTable("model");
                });

            modelBuilder.Entity("AutoServis.Models.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Naziv")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("grad");
                });

            modelBuilder.Entity("AutoServis.Models.Klijent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DatumRegistracije");

                    b.Property<int>("OsobaId");

                    b.HasKey("Id");

                    b.HasIndex("OsobaId")
                        .IsUnique();

                    b.ToTable("klijent");
                });

            modelBuilder.Entity("AutoServis.Models.Osoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adresa");

                    b.Property<int>("GradId");

                    b.Property<string>("Ime");

                    b.Property<string>("KorisnickoIme");

                    b.Property<string>("Lozinka");

                    b.Property<string>("Prezime");

                    b.Property<string>("Telefon");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.ToTable("osoba");
                });

            modelBuilder.Entity("AutoServis.Models.Poslovnica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adresa");

                    b.Property<int>("GradId");

                    b.Property<string>("Naziv");

                    b.Property<string>("Telefon");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.ToTable("poslovnica");
                });

            modelBuilder.Entity("AutoServis.Models.Uposlenik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DatumRodjenja");

                    b.Property<DateTime>("DatumZaposljavanja");

                    b.Property<string>("JMBG");

                    b.Property<int?>("OsobaId");

                    b.Property<int>("PoslovnicaId");

                    b.Property<int>("VrstaUposlenikaId");

                    b.HasKey("Id");

                    b.HasIndex("OsobaId")
                        .IsUnique()
                        .HasFilter("[OsobaId] IS NOT NULL");

                    b.HasIndex("PoslovnicaId");

                    b.HasIndex("VrstaUposlenikaId");

                    b.ToTable("uposlenik");
                });

            modelBuilder.Entity("AutoServis.Models.VrstaUposlenika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Naziv");

                    b.HasKey("Id");

                    b.ToTable("vrstauposlenika");
                });

            modelBuilder.Entity("AutoServis.Models.Dio", b =>
                {
                    b.HasOne("AutoServis.Models.Model", "model")
                        .WithMany()
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AutoServis.Models.Model", b =>
                {
                    b.HasOne("AutoServis.Models.Marka", "marka")
                        .WithMany()
                        .HasForeignKey("MarkaID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AutoServis.Models.Klijent", b =>
                {
                    b.HasOne("AutoServis.Models.Osoba", "Osoba")
                        .WithOne("Klijent")
                        .HasForeignKey("AutoServis.Models.Klijent", "OsobaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AutoServis.Models.Osoba", b =>
                {
                    b.HasOne("AutoServis.Models.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AutoServis.Models.Poslovnica", b =>
                {
                    b.HasOne("AutoServis.Models.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AutoServis.Models.Uposlenik", b =>
                {
                    b.HasOne("AutoServis.Models.Osoba", "Osoba")
                        .WithOne("Uposlenik")
                        .HasForeignKey("AutoServis.Models.Uposlenik", "OsobaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoServis.Models.Poslovnica", "Poslovnica")
                        .WithMany()
                        .HasForeignKey("PoslovnicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoServis.Models.VrstaUposlenika", "VrstaUposlenika")
                        .WithMany()
                        .HasForeignKey("VrstaUposlenikaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
